import avatar1 from '@images/avatars/avatar-1.png'
import avatar2 from '@images/avatars/avatar-2.png'
import avatar3 from '@images/avatars/avatar-3.png'
import avatar4 from '@images/avatars/avatar-4.png'
import avatar5 from '@images/avatars/avatar-5.png'
import avatar6 from '@images/avatars/avatar-6.png'
import avatar7 from '@images/avatars/avatar-7.png'
import avatar8 from '@images/avatars/avatar-8.png'
import mock from '@/@fake-db/mock'

const users = [
  {
    id: 1,
    avatar: '',
    fullName: '김민준',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-03-07',
    bs: 'B',
    contact: '010-2329-1510',
    remarks: '',
    salvationDate: '2019-05-12',
    birthDate: '2001-04-15',
    age: 26,
    serviceTeam: '찬양팀',
    collegeTeam: 'A팀',
    occupation: '학생',
    workplaceName: '아주대학교',
    address: '경기도 수원시 팔달구 인계로 123',
    parish: '1교구',
    email: 'kminjun@example.com',
    username: 'kminjun',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 2,
    avatar: avatar1,
    fullName: '이서연',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '사랑부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2020-09-13',
    bs: 'S',
    contact: '010-4726-9137',
    remarks: '찬양팀 리더',
    salvationDate: '2018-11-20',
    birthDate: '2002-08-22',
    age: 25,
    serviceTeam: '봉사팀',
    collegeTeam: 'B팀',
    occupation: '학생',
    workplaceName: '경기대학교',
    address: '경기도 수원시 영통구 영통로 45',
    parish: '2교구',
    email: 'lsy@example.com',
    username: 'lseoyeon',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 3,
    avatar: avatar1,
    fullName: '박지호',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2019-06-02',
    bs: 'B',
    contact: '010-3214-4599',
    remarks: '',
    salvationDate: '2017-03-15',
    birthDate: '1998-03-07',
    age: 29,
    serviceTeam: '예배팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '삼성전자',
    address: '경기도 수원시 영통구 삼성로 129',
    parish: '1교구',
    email: 'pjh@example.com',
    username: 'parkjiho',
    role: 'maintainer',
    status: 'active',
  },
  {
    id: 4,
    avatar: avatar3,
    fullName: '최수아',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2022-02-20',
    bs: 'S',
    contact: '010-9236-6806',
    remarks: '',
    salvationDate: '2020-08-09',
    birthDate: '2000-11-30',
    age: 27,
    serviceTeam: '봉사팀',
    collegeTeam: 'C팀',
    occupation: '학생',
    workplaceName: '수원대학교',
    address: '경기도 수원시 권선구 권선로 88',
    parish: '3교구',
    email: 'csua@example.com',
    username: 'choiSua',
    role: 'subscriber',
    status: 'inactive',
  },
  {
    id: 5,
    avatar: avatar1,
    fullName: '정도현',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2018-11-05',
    bs: 'B',
    contact: '010-6699-1078',
    remarks: '청년부 임원',
    salvationDate: '2016-04-17',
    birthDate: '1997-06-18',
    age: 30,
    serviceTeam: '전도팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'LG전자',
    address: '경기도 수원시 장안구 장안로 210',
    parish: '2교구',
    email: 'jdh@example.com',
    username: 'jungDH',
    role: 'editor',
    status: 'active',
  },
  {
    id: 6,
    avatar: '',
    fullName: '강하은',
    currentDepartment: '사랑부',
    departmentHistory: [
      { year: 2024, department: '사랑부' },
      { year: 2025, department: '사랑부' },
      { year: 2026, department: '사랑부' },
    ],
    transferInDate: '2023-03-05',
    bs: 'S',
    contact: '010-9589-3093',
    remarks: '',
    salvationDate: '',
    birthDate: '2007-02-14',
    age: 20,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원여자고등학교',
    address: '경기도 수원시 팔달구 효원로 77',
    parish: '4교구',
    email: 'khe@example.com',
    username: 'kangHE',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 7,
    avatar: '',
    fullName: '조민서',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-11',
    bs: 'S',
    contact: '010-8259-8152',
    remarks: '',
    salvationDate: '2021-01-03',
    birthDate: '2001-09-05',
    age: 26,
    serviceTeam: '봉사팀',
    collegeTeam: 'A팀',
    occupation: '학생',
    workplaceName: '한양대학교(에리카)',
    address: '경기도 수원시 영통구 동수원로 394',
    parish: '1교구',
    email: 'jms@example.com',
    username: 'choMS',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 8,
    avatar: avatar4,
    fullName: '윤지우',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2017-08-20',
    bs: 'B',
    contact: '010-1874-0934',
    remarks: '구역장',
    salvationDate: '2015-06-28',
    birthDate: '1996-12-20',
    age: 31,
    serviceTeam: '행정팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'SK하이닉스',
    address: '경기도 수원시 권선구 수인로 43',
    parish: '3교구',
    email: 'yjw@example.com',
    username: 'yoonJW',
    role: 'maintainer',
    status: 'active',
  },
  {
    id: 9,
    avatar: avatar2,
    fullName: '임수현',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-03-06',
    bs: 'S',
    contact: '010-9781-5443',
    remarks: '',
    salvationDate: '2021-07-18',
    birthDate: '2002-05-11',
    age: 25,
    serviceTeam: '찬양팀',
    collegeTeam: 'B팀',
    occupation: '학생',
    workplaceName: '성균관대학교',
    address: '경기도 수원시 장안구 서부로 2066',
    parish: '2교구',
    email: 'lsh@example.com',
    username: 'limSH',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 10,
    avatar: avatar5,
    fullName: '한예린',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2020-05-17',
    bs: 'S',
    contact: '010-5892-6732',
    remarks: '',
    salvationDate: '2018-09-30',
    birthDate: '1999-01-25',
    age: 28,
    serviceTeam: '봉사팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '수원시청',
    address: '경기도 수원시 팔달구 효원로 241',
    parish: '4교구',
    email: 'hyr@example.com',
    username: 'hanYR',
    role: 'maintainer',
    status: 'inactive',
  },
  {
    id: 11,
    avatar: avatar4,
    fullName: '오준혁',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-04',
    bs: 'B',
    contact: '010-1765-6824',
    remarks: '',
    salvationDate: '2022-01-09',
    birthDate: '2003-07-08',
    age: 24,
    serviceTeam: '전도팀',
    collegeTeam: 'C팀',
    occupation: '학생',
    workplaceName: '아주대학교',
    address: '경기도 수원시 영통구 월드컵로 206',
    parish: '1교구',
    email: 'ojh@example.com',
    username: 'ohJH',
    role: 'subscriber',
    status: 'inactive',
  },
  {
    id: 12,
    avatar: avatar5,
    fullName: '신채원',
    currentDepartment: '사랑부',
    departmentHistory: [
      { year: 2024, department: '사랑부' },
      { year: 2025, department: '사랑부' },
      { year: 2026, department: '사랑부' },
    ],
    transferInDate: '2023-03-12',
    bs: 'S',
    contact: '010-2344-0600',
    remarks: '부모님과 함께 출석',
    salvationDate: '',
    birthDate: '2006-10-15',
    age: 21,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원고등학교',
    address: '경기도 수원시 권선구 세화로 155',
    parish: '3교구',
    email: 'scw@example.com',
    username: 'shinCW',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 13,
    avatar: avatar7,
    fullName: '권지훈',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-06-20',
    bs: 'B',
    contact: '010-9072-5083',
    remarks: '',
    salvationDate: '2019-12-25',
    birthDate: '2002-03-22',
    age: 25,
    serviceTeam: '예배팀',
    collegeTeam: 'A팀',
    occupation: '학생',
    workplaceName: '가천대학교',
    address: '경기도 수원시 장안구 파장천로 33',
    parish: '2교구',
    email: 'kwjh@example.com',
    username: 'kwonJH',
    role: 'subscriber',
    status: 'inactive',
  },
  {
    id: 14,
    avatar: avatar6,
    fullName: '황소희',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2019-09-08',
    bs: 'S',
    contact: '010-1671-7392',
    remarks: '찬양 세션 담당',
    salvationDate: '2017-07-14',
    birthDate: '1998-09-14',
    age: 29,
    serviceTeam: '찬양팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'KT',
    address: '경기도 수원시 팔달구 중부대로 180',
    parish: '4교구',
    email: 'hsh@example.com',
    username: 'hwangSH',
    role: 'author',
    status: 'active',
  },
  {
    id: 15,
    avatar: avatar2,
    fullName: '송민재',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2022, department: '사랑부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-03-14',
    bs: 'B',
    contact: '010-3174-6565',
    remarks: '',
    salvationDate: '2020-02-16',
    birthDate: '2001-12-03',
    age: 26,
    serviceTeam: '봉사팀',
    collegeTeam: 'D팀',
    occupation: '학생',
    workplaceName: '경기대학교',
    address: '경기도 수원시 영통구 봉영로 37',
    parish: '1교구',
    email: 'smj@example.com',
    username: 'songMJ',
    role: 'maintainer',
    status: 'active',
  },
  {
    id: 16,
    avatar: avatar6,
    fullName: '유하린',
    currentDepartment: '사랑부',
    departmentHistory: [
      { year: 2024, department: '사랑부' },
      { year: 2025, department: '사랑부' },
      { year: 2026, department: '사랑부' },
    ],
    transferInDate: '2024-03-03',
    bs: 'S',
    contact: '010-5906-1056',
    remarks: '새신자',
    salvationDate: '',
    birthDate: '2007-04-19',
    age: 20,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원외국어고등학교',
    address: '경기도 수원시 권선구 호매실로 46',
    parish: '3교구',
    email: 'yhl@example.com',
    username: 'youHL',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 17,
    avatar: '',
    fullName: '전성민',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2018-04-22',
    bs: 'B',
    contact: '010-5532-9905',
    remarks: '행정팀 리더',
    salvationDate: '2015-09-06',
    birthDate: '1997-08-27',
    age: 30,
    serviceTeam: '행정팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '현대자동차',
    address: '경기도 수원시 장안구 정조로 815',
    parish: '2교구',
    email: 'jsm@example.com',
    username: 'jeonSM',
    role: 'maintainer',
    status: 'active',
  },
  {
    id: 18,
    avatar: avatar7,
    fullName: '남지수',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-18',
    bs: 'S',
    contact: '010-9019-9287',
    remarks: '',
    salvationDate: '2022-03-27',
    birthDate: '2003-01-16',
    age: 24,
    serviceTeam: '전도팀',
    collegeTeam: 'B팀',
    occupation: '학생',
    workplaceName: '수원대학교',
    address: '경기도 수원시 팔달구 신풍로 23',
    parish: '4교구',
    email: 'njs@example.com',
    username: 'namJS',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 19,
    avatar: '',
    fullName: '서준영',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2016-07-10',
    bs: 'B',
    contact: '010-5245-6057',
    remarks: '청년부 부장',
    salvationDate: '2013-11-02',
    birthDate: '1995-05-30',
    age: 32,
    serviceTeam: '예배팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '삼성전자',
    address: '경기도 수원시 영통구 광교중앙로 145',
    parish: '1교구',
    email: 'sjy@example.com',
    username: 'seoJY',
    role: 'admin',
    status: 'active',
  },
  {
    id: 20,
    avatar: avatar6,
    fullName: '배은지',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-03-06',
    bs: 'S',
    contact: '010-5696-1292',
    remarks: '',
    salvationDate: '2021-05-23',
    birthDate: '2002-11-08',
    age: 25,
    serviceTeam: '찬양팀',
    collegeTeam: 'C팀',
    occupation: '학생',
    workplaceName: '한신대학교',
    address: '경기도 수원시 권선구 오목천로 68',
    parish: '3교구',
    email: 'bej@example.com',
    username: 'baeEJ',
    role: 'subscriber',
    status: 'inactive',
  },
  {
    id: 21,
    avatar: avatar1,
    fullName: '홍민우',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2019-11-17',
    bs: 'B',
    contact: '010-8295-0057',
    remarks: '',
    salvationDate: '2017-08-13',
    birthDate: '1998-07-22',
    age: 29,
    serviceTeam: '봉사팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'LG전자',
    address: '경기도 수원시 팔달구 우만로 119',
    parish: '2교구',
    email: 'hmw@example.com',
    username: 'hongMW',
    role: 'admin',
    status: 'active',
  },
  {
    id: 22,
    avatar: avatar8,
    fullName: '문소연',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-25',
    bs: 'S',
    contact: '010-5936-0222',
    remarks: '',
    salvationDate: '2021-10-31',
    birthDate: '2001-02-17',
    age: 26,
    serviceTeam: '전도팀',
    collegeTeam: 'A팀',
    occupation: '학생',
    workplaceName: '아주대학교',
    address: '경기도 수원시 영통구 대학로 17',
    parish: '4교구',
    email: 'msy@example.com',
    username: 'moonSY',
    role: 'editor',
    status: 'inactive',
  },
  {
    id: 23,
    avatar: avatar3,
    fullName: '류재원',
    currentDepartment: '사랑부',
    departmentHistory: [
      { year: 2024, department: '사랑부' },
      { year: 2025, department: '사랑부' },
      { year: 2026, department: '사랑부' },
    ],
    transferInDate: '2023-09-10',
    bs: 'B',
    contact: '010-2548-4107',
    remarks: '',
    salvationDate: '',
    birthDate: '2009-06-25',
    age: 18,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원중학교',
    address: '경기도 수원시 장안구 화산로 37',
    parish: '1교구',
    email: 'rjw@example.com',
    username: 'ryuJW',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 24,
    avatar: avatar2,
    fullName: '안수빈',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2020-08-30',
    bs: 'S',
    contact: '010-7007-7498',
    remarks: '',
    salvationDate: '2018-12-16',
    birthDate: '1999-10-04',
    age: 28,
    serviceTeam: '예배팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'SK하이닉스',
    address: '경기도 수원시 권선구 덕영대로 924',
    parish: '3교구',
    email: 'asb@example.com',
    username: 'anSB',
    role: 'admin',
    status: 'pending',
  },
  {
    id: 25,
    avatar: '',
    fullName: '고태양',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2022, department: '사랑부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-04-18',
    bs: 'B',
    contact: '010-2275-1841',
    remarks: '',
    salvationDate: '2020-06-14',
    birthDate: '2000-03-12',
    age: 27,
    serviceTeam: '행정팀',
    collegeTeam: 'D팀',
    occupation: '학생',
    workplaceName: '성균관대학교',
    address: '경기도 수원시 팔달구 매산로 45',
    parish: '2교구',
    email: 'gty@example.com',
    username: 'goTY',
    role: 'admin',
    status: 'pending',
  },
  {
    id: 26,
    avatar: avatar4,
    fullName: '노다은',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2017-11-26',
    bs: 'S',
    contact: '010-5825-1324',
    remarks: '구역장',
    salvationDate: '2015-04-05',
    birthDate: '1996-08-09',
    age: 31,
    serviceTeam: '찬양팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '수원시청',
    address: '경기도 수원시 장안구 수성로 176',
    parish: '4교구',
    email: 'nde@example.com',
    username: 'noDE',
    role: 'admin',
    status: 'inactive',
  },
  {
    id: 27,
    avatar: avatar5,
    fullName: '심재훈',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-03-27',
    bs: 'B',
    contact: '010-1374-5393',
    remarks: '',
    salvationDate: '2021-09-12',
    birthDate: '2002-04-28',
    age: 25,
    serviceTeam: '봉사팀',
    collegeTeam: 'B팀',
    occupation: '학생',
    workplaceName: '경기대학교',
    address: '경기도 수원시 영통구 이의동 906',
    parish: '1교구',
    email: 'sjh@example.com',
    username: 'shimJH',
    role: 'editor',
    status: 'active',
  },
  {
    id: 28,
    avatar: '',
    fullName: '구민아',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2019-05-12',
    bs: 'S',
    contact: '010-4124-0854',
    remarks: '',
    salvationDate: '2016-02-21',
    birthDate: '1997-12-15',
    age: 30,
    serviceTeam: '전도팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'KT',
    address: '경기도 수원시 권선구 금호로 79',
    parish: '3교구',
    email: 'gma@example.com',
    username: 'kuMA',
    role: 'maintainer',
    status: 'active',
  },
  {
    id: 29,
    avatar: avatar7,
    fullName: '원태경',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2022, department: '사랑부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-09-05',
    bs: 'B',
    contact: '010-1706-1520',
    remarks: '',
    salvationDate: '2020-04-19',
    birthDate: '2001-07-01',
    age: 26,
    serviceTeam: '예배팀',
    collegeTeam: 'C팀',
    occupation: '학생',
    workplaceName: '가천대학교',
    address: '경기도 수원시 팔달구 창룡대로 19',
    parish: '2교구',
    email: 'wtk@example.com',
    username: 'wonTK',
    role: 'maintainer',
    status: 'active',
  },
  {
    id: 30,
    avatar: '',
    fullName: '방지영',
    currentDepartment: '은혜부',
    departmentHistory: [
      { year: 2025, department: '은혜부' },
      { year: 2026, department: '은혜부' },
    ],
    transferInDate: '2024-09-08',
    bs: 'S',
    contact: '010-3328-1983',
    remarks: '새신자',
    salvationDate: '',
    birthDate: '2007-09-18',
    age: 20,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원여자고등학교',
    address: '경기도 수원시 영통구 신동 512',
    parish: '4교구',
    email: 'bjy@example.com',
    username: 'bangJY',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 31,
    avatar: avatar1,
    fullName: '선하준',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2020-01-19',
    bs: 'B',
    contact: '010-5513-7460',
    remarks: '',
    salvationDate: '2018-07-07',
    birthDate: '1998-11-23',
    age: 29,
    serviceTeam: '행정팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '현대자동차',
    address: '경기도 수원시 장안구 조원동 1178',
    parish: '1교구',
    email: 'shj@example.com',
    username: 'sunHJ',
    role: 'admin',
    status: 'pending',
  },
  {
    id: 32,
    avatar: avatar5,
    fullName: '천소율',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-03-20',
    bs: 'S',
    contact: '010-9748-0911',
    remarks: '',
    salvationDate: '2021-11-28',
    birthDate: '2003-02-07',
    age: 24,
    serviceTeam: '찬양팀',
    collegeTeam: 'A팀',
    occupation: '학생',
    workplaceName: '수원대학교',
    address: '경기도 수원시 권선구 평동로 5',
    parish: '3교구',
    email: 'csy@example.com',
    username: 'chunSY',
    role: 'editor',
    status: 'pending',
  },
  {
    id: 33,
    avatar: avatar8,
    fullName: '경민호',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2015-08-16',
    bs: 'B',
    contact: '010-8418-3339',
    remarks: '청년부 임원',
    salvationDate: '2013-03-24',
    birthDate: '1995-04-14',
    age: 32,
    serviceTeam: '봉사팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '삼성전자',
    address: '경기도 수원시 팔달구 인계동 935',
    parish: '2교구',
    email: 'kmh@example.com',
    username: 'kyungMH',
    role: 'admin',
    status: 'active',
  },
  {
    id: 34,
    avatar: avatar4,
    fullName: '변채은',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-11',
    bs: 'S',
    contact: '010-7648-7351',
    remarks: '',
    salvationDate: '2022-01-15',
    birthDate: '2002-08-31',
    age: 25,
    serviceTeam: '전도팀',
    collegeTeam: 'D팀',
    occupation: '학생',
    workplaceName: '한양대학교(에리카)',
    address: '경기도 수원시 영통구 망포동 327',
    parish: '4교구',
    email: 'bce@example.com',
    username: 'byunCE',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 35,
    avatar: '',
    fullName: '마준서',
    currentDepartment: '은혜부',
    departmentHistory: [
      { year: 2024, department: '은혜부' },
      { year: 2025, department: '은혜부' },
      { year: 2026, department: '은혜부' },
    ],
    transferInDate: '2023-09-03',
    bs: 'B',
    contact: '010-3505-8520',
    remarks: '',
    salvationDate: '',
    birthDate: '2006-12-10',
    age: 21,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원고등학교',
    address: '경기도 수원시 장안구 천천동 66',
    parish: '1교구',
    email: 'mjs@example.com',
    username: 'maJS',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 36,
    avatar: '',
    fullName: '봉하영',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2020-04-26',
    bs: 'S',
    contact: '010-8829-2180',
    remarks: '',
    salvationDate: '2018-02-11',
    birthDate: '1999-06-26',
    age: 28,
    serviceTeam: '예배팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'LG전자',
    address: '경기도 수원시 권선구 세류동 1152',
    parish: '3교구',
    email: 'bhy@example.com',
    username: 'bongHY',
    role: 'subscriber',
    status: 'inactive',
  },
  {
    id: 37,
    avatar: avatar1,
    fullName: '설도윤',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2022, department: '사랑부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-06-13',
    bs: 'B',
    contact: '010-6103-1024',
    remarks: '',
    salvationDate: '2020-10-04',
    birthDate: '2001-10-19',
    age: 26,
    serviceTeam: '행정팀',
    collegeTeam: 'B팀',
    occupation: '학생',
    workplaceName: '아주대학교',
    address: '경기도 수원시 팔달구 향교로 88',
    parish: '2교구',
    email: 'sdy@example.com',
    username: 'sulDY',
    role: 'admin',
    status: 'inactive',
  },
  {
    id: 38,
    avatar: avatar1,
    fullName: '음민지',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2018-07-29',
    bs: 'S',
    contact: '010-3652-2986',
    remarks: '찬양팀 세션',
    salvationDate: '2016-01-17',
    birthDate: '1997-03-05',
    age: 30,
    serviceTeam: '찬양팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'SK하이닉스',
    address: '경기도 수원시 영통구 영통동 984',
    parish: '4교구',
    email: 'emj@example.com',
    username: 'eumMJ',
    role: 'maintainer',
    status: 'inactive',
  },
  {
    id: 39,
    avatar: '',
    fullName: '탁재현',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-03-13',
    bs: 'B',
    contact: '010-5317-0928',
    remarks: '',
    salvationDate: '2021-12-05',
    birthDate: '2002-01-13',
    age: 25,
    serviceTeam: '봉사팀',
    collegeTeam: 'C팀',
    occupation: '학생',
    workplaceName: '성균관대학교',
    address: '경기도 수원시 장안구 율전동 300',
    parish: '1교구',
    email: 'tjh@example.com',
    username: 'takJH',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 40,
    avatar: avatar6,
    fullName: '곽소현',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2020-02-23',
    bs: 'S',
    contact: '010-3121-2638',
    remarks: '',
    salvationDate: '2018-06-16',
    birthDate: '1998-05-20',
    age: 29,
    serviceTeam: '전도팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '수원시청',
    address: '경기도 수원시 권선구 고색동 893',
    parish: '3교구',
    email: 'ksh@example.com',
    username: 'kwakSH',
    role: 'author',
    status: 'active',
  },
  {
    id: 41,
    avatar: '',
    fullName: '장민호',
    currentDepartment: '은혜부',
    departmentHistory: [
      { year: 2025, department: '은혜부' },
      { year: 2026, department: '은혜부' },
    ],
    transferInDate: '2025-03-02',
    bs: 'B',
    contact: '010-3153-3578',
    remarks: '새신자',
    salvationDate: '',
    birthDate: '2010-08-07',
    age: 17,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원중학교',
    address: '경기도 수원시 팔달구 지동 416',
    parish: '2교구',
    email: 'jmh@example.com',
    username: 'jangMH',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 42,
    avatar: '',
    fullName: '차서윤',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-04',
    bs: 'S',
    contact: '010-3231-6741',
    remarks: '',
    salvationDate: '2022-04-10',
    birthDate: '2003-11-24',
    age: 24,
    serviceTeam: '예배팀',
    collegeTeam: 'A팀',
    occupation: '학생',
    workplaceName: '한신대학교',
    address: '경기도 수원시 영통구 하동 690',
    parish: '4교구',
    email: 'csy2@example.com',
    username: 'chaSY',
    role: 'editor',
    status: 'inactive',
  },
  {
    id: 43,
    avatar: '',
    fullName: '주지우',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2017-06-25',
    bs: 'B',
    contact: '010-2429-0916',
    remarks: '',
    salvationDate: '2014-09-28',
    birthDate: '1996-07-17',
    age: 31,
    serviceTeam: '행정팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'KT',
    address: '경기도 수원시 장안구 송죽동 315',
    parish: '1교구',
    email: 'jjw@example.com',
    username: 'juJW',
    role: 'admin',
    status: 'inactive',
  },
  {
    id: 44,
    avatar: '',
    fullName: '도수현',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2022, department: '사랑부' },
      { year: 2023, department: '믿음부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2021-03-21',
    bs: 'B',
    contact: '010-5317-8335',
    remarks: '',
    salvationDate: '2020-07-05',
    birthDate: '2001-04-29',
    age: 26,
    serviceTeam: '찬양팀',
    collegeTeam: 'D팀',
    occupation: '학생',
    workplaceName: '경기대학교',
    address: '경기도 수원시 권선구 구운동 231',
    parish: '3교구',
    email: 'dsh@example.com',
    username: 'doSH',
    role: 'author',
    status: 'active',
  },
  {
    id: 45,
    avatar: avatar3,
    fullName: '표예린',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '믿음부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2020-10-11',
    bs: 'S',
    contact: '010-6593-6808',
    remarks: '',
    salvationDate: '2018-05-20',
    birthDate: '1999-09-11',
    age: 28,
    serviceTeam: '봉사팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '현대자동차',
    address: '경기도 수원시 팔달구 화서동 527',
    parish: '2교구',
    email: 'pyr@example.com',
    username: 'pyoYR',
    role: 'subscriber',
    status: 'pending',
  },
  {
    id: 46,
    avatar: '',
    fullName: '사공민준',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-09-18',
    bs: 'B',
    contact: '010-2005-2264',
    remarks: '',
    salvationDate: '2022-02-27',
    birthDate: '2002-06-03',
    age: 25,
    serviceTeam: '전도팀',
    collegeTeam: 'B팀',
    occupation: '학생',
    workplaceName: '가천대학교',
    address: '경기도 수원시 영통구 광교동 106',
    parish: '4교구',
    email: 'sgmj@example.com',
    username: 'sagongMJ',
    role: 'maintainer',
    status: 'pending',
  },
  {
    id: 47,
    avatar: avatar1,
    fullName: '남궁서아',
    currentDepartment: '은혜부',
    departmentHistory: [
      { year: 2024, department: '은혜부' },
      { year: 2025, department: '은혜부' },
      { year: 2026, department: '은혜부' },
    ],
    transferInDate: '2024-03-10',
    bs: 'S',
    contact: '010-4781-0020',
    remarks: '',
    salvationDate: '',
    birthDate: '2009-12-21',
    age: 18,
    serviceTeam: '',
    collegeTeam: '',
    occupation: '학생',
    workplaceName: '수원여자중학교',
    address: '경기도 수원시 장안구 파장동 155',
    parish: '1교구',
    email: 'ngsa@example.com',
    username: 'namgungSA',
    role: 'subscriber',
    status: 'active',
  },
  {
    id: 48,
    avatar: '',
    fullName: '제갈도현',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2019-02-17',
    bs: 'B',
    contact: '010-3442-7270',
    remarks: '',
    salvationDate: '2016-10-09',
    birthDate: '1997-10-08',
    age: 30,
    serviceTeam: '예배팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: '삼성전자',
    address: '경기도 수원시 팔달구 우만동 734',
    parish: '3교구',
    email: 'jgdh@example.com',
    username: 'jegalDH',
    role: 'admin',
    status: 'pending',
  },
  {
    id: 49,
    avatar: '',
    fullName: '황보하은',
    currentDepartment: '믿음부',
    departmentHistory: [
      { year: 2023, department: '사랑부' },
      { year: 2024, department: '믿음부' },
      { year: 2025, department: '믿음부' },
      { year: 2026, department: '믿음부' },
    ],
    transferInDate: '2022-03-27',
    bs: 'S',
    contact: '010-6946-1275',
    remarks: '',
    salvationDate: '2021-08-22',
    birthDate: '2003-03-15',
    age: 24,
    serviceTeam: '행정팀',
    collegeTeam: 'C팀',
    occupation: '학생',
    workplaceName: '수원대학교',
    address: '경기도 수원시 권선구 입북동 87',
    parish: '2교구',
    email: 'hbhe@example.com',
    username: 'hwangboHE',
    role: 'subscriber',
    status: 'inactive',
  },
  {
    id: 50,
    avatar: avatar2,
    fullName: '선우지훈',
    currentDepartment: '소망부',
    departmentHistory: [
      { year: 2022, department: '소망부' },
      { year: 2023, department: '소망부' },
      { year: 2024, department: '소망부' },
      { year: 2025, department: '소망부' },
      { year: 2026, department: '소망부' },
    ],
    transferInDate: '2016-09-04',
    bs: 'B',
    contact: '010-3972-5153',
    remarks: '청년부 임원',
    salvationDate: '2013-12-15',
    birthDate: '1995-01-27',
    age: 32,
    serviceTeam: '찬양팀',
    collegeTeam: '',
    occupation: '직장인',
    workplaceName: 'LG전자',
    address: '경기도 수원시 영통구 원천동 480',
    parish: '4교구',
    email: 'swjh@example.com',
    username: 'sunwooJH',
    role: 'editor',
    status: 'active',
  },
]


// 👉 성도 목록 반환
mock.onGet('/apps/users/list').reply(config => {
  const {
    q = '',
    currentDepartment = null,
    parish = null,
    occupation = null,
    status = null,
    perPage = 10,
    currentPage = 1,
  } = config.params ?? {}

  const queryLower = q.toLowerCase()

  let filteredUsers = users.filter(user =>
    (user.fullName.toLowerCase().includes(queryLower) || user.contact.includes(queryLower))
    && user.currentDepartment === (currentDepartment || user.currentDepartment)
    && user.parish === (parish || user.parish)
    && user.occupation === (occupation || user.occupation)
    && user.status === (status || user.status),
  ).reverse()

  const totalPage = Math.round(filteredUsers.length / perPage) ? Math.round(filteredUsers.length / perPage) : 1
  const totalUsers = filteredUsers.length

  if (perPage) {
    const firstIndex = (currentPage - 1) * perPage
    const lastIndex = perPage * currentPage

    filteredUsers = filteredUsers.slice(firstIndex, lastIndex)
  }

  return [200, { users: filteredUsers, totalPage, totalUsers }]
})

// 👉 성도 추가
mock.onPost('/apps/users/user').reply(config => {
  const { user } = JSON.parse(config.data)
  const { length } = users
  let lastIndex = 0
  if (length)
    lastIndex = users[length - 1].id
  user.id = lastIndex + 1
  users.push(user)

  return [201, { user }]
})

// 👉 성도 상세 조회
mock.onGet(/\/apps\/users\/\d+/).reply(config => {
  const userId = config.url?.substring(config.url.lastIndexOf('/') + 1)
  const Id = Number(userId)
  const userIndex = users.findIndex(e => e.id === Id)
  const user = users[userIndex]

  if (user)
    return [200, user]

  return [404]
})
